In [1]:
import numpy as np

# The Basics of NumPy Arrays

### Data Types of in numpy

In [17]:
array1 = np.array([1,2,3,4])
print(array1)
print(type(array1))
print(type(array1[0]))

'''
If even one element in the ndarray is of a different data type then it will
upcast based on the hierarchy below from lowert to highest

boolean > int > float > complex

'''

a = 10  # int
b = 3.14  # float
c = 2 + 1j  # complex

# Upcasting hierarchy:
# int -> float -> complex

result1 = a + b  # int is upcasted to float
result2 = a + c  # int is upcasted to complex
print("\n")

print(result1)  # Output: 13.14
print(result2)  # Output: (12+1j)


array2 = np.array([1,2,3.14,4])
print("\n")
print(array2)
print(str(type(array2[2])))
print(type(array2[0]))

#You can explicitly set the data type by using the method below

array3 = np.array([1,2,3,3.14,4], dtype =  np.int32)
print("\n")
print(array3)
print(str(type(array2[2])))
print(type(array2[0]))


[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int32'>


13.14
(12+1j)


[1.   2.   3.14 4.  ]
<class 'numpy.float64'>
<class 'numpy.float64'>


[1 2 3 3 4]
<class 'numpy.float64'>
<class 'numpy.float64'>


### Accessing array and creating substring

In [49]:
import random
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
print("x1: \n", x1)
print("\n")
print("x2: \n", x2)
print("\n")
print("x3: \n", x3)

print("\n\n")

#Array_Name[row, column]
print(x2[2,0]) #This prints the element that is at the 2nd row and the first element
print(x2[2,-1]) #This prints the element that is at the 2nd row and the first element from the end of that row

#To reverse a array
print ("\n\n")
print(x1[::-1])
print ("\n")
print(x2[::-1, ::-1]) #This first reverses the rows then also reverses the colums

#Accessing and extracting a specific subarray
print("\n\n")
print(x2[:1,:3]) #Print subarray containing elements of the 1st row and up to 3rd column
print("\n")
print(x2[:3, :2]) #Print subarray containing elements of upto 3nd row and up to 2nd column
subarray_2x2 = x2[:3, :2]
print("\nSubarray of 3x2 of array x2 using extraction: \n" + str(subarray_2x2))
subarray_2x2[0,0] = 99
print("\nSubarray of extracted 3x2 but changed 0,0=99: \n" + str(subarray_2x2))
print("\nWe see that change reflects on x2: \n" + str(x2))
subarray_3x2_copy = x2[:3, :2].copy()
subarray_3x2_copy[1,1] = 99
print("\nSubarray of extracted 3x2 as a copy with changed 1,1=99: \n" + str(subarray_3x2_copy))
print("\nWe see that change not reflects on x2: \n" + str(x2))


#To print/access a entire row or a entire column in the array
print("\n\n")
print(x2[:,1]) #Print 2nd column
print(x2[2, :]) #Prints the 3rd row

x1: 
 [5 0 3 3 7 9]


x2: 
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


x3: 
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]



1
7



[9 7 3 3 0 5]


[[7 7 6 1]
 [8 8 6 7]
 [4 2 5 3]]



[[3 5 2]]


[[3 5]
 [7 6]
 [1 6]]

Subarray of 3x2 of array x2 using extraction: 
[[3 5]
 [7 6]
 [1 6]]

Subarray of extracted 3x2 but changed 0,0=99: 
[[99  5]
 [ 7  6]
 [ 1  6]]

We see that change reflects on x2: 
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

Subarray of extracted 3x2 as a copy with changed 1,1=99: 
[[99  5]
 [ 7 99]
 [ 1  6]]

We see that change not reflects on x2: 
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]



[5 6 6]
[1 6 7 7]


### Concatenation and splitting of arrays

In [78]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([1, 1, 1])

print("x: " + str(x))
print("y: " + str(y))
print("z: " + str(z))

print("\n\nx + y: " + str(np.concatenate([x, y])))
print("x + y + z: " + str(np.concatenate([x, y, z])))

grid = np.array([[1, 2, 3], [4, 5, 6]])
print("\n\nGrid: \n" + str(grid))
print("\nGrid + grid: \n" + str(np.concatenate([grid, grid]))) #Default axis is 0 meaning it will concatonate by rows (one array below another)
print("\nGrid + grid: \n" + str(np.concatenate([grid, grid], axis= 1))) #Change axis to 1 meaning that it will concatonate based on column (one array next to eachother)

#Is using arrays of varying dimenttions then use vstack (function that stacks vertically) and hstack (function that stacks horizontally)
x = np.array([1, 2, 3])
y = np.array([[99], [99]])
grid = np.array([[9, 8, 7], [6, 5, 4]])
print("\n\nx: " + str(x))
print("\ny: \n" + str(y))
print("\ngrid: \n" + str(grid))
print("\nVertical stacked using vstack of x and grid: \n" + str(np.vstack([x, grid])))
print("\nHorizontally stacked using hstack of y and grid: \n" + str(np.hstack([grid, y])))

x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) #Makes 3 different arrays having the first split at index 3 (exclusive) and second at index 5 (exclusive)
print("\n\n")
print("x: " + str(x))
print("\nAll the arrays are splitted arrays are given below: ")
print(x1, x2, x3)

#You can also use vsplit (vertically splitting) and hsplit (horizontal split)
grid = np.arange(16).reshape((4, 4))
print("\n\ngrid: \n" + str(grid))
upper, lower = np.vsplit(grid, [2])
print("\nUsing vsplit (upper then lower) split at index 2 (exclusive): \n")
print(upper)
print("\n")
print(lower)

left, right = np.hsplit(grid, [2])
print("\nUsing hsplit (left then right) split at index 2 (exclusive): \n")
print(left)
print("\n")
print(right)

x: [1 2 3]
y: [3 2 1]
z: [1 1 1]


x + y: [1 2 3 3 2 1]
x + y + z: [1 2 3 3 2 1 1 1 1]


Grid: 
[[1 2 3]
 [4 5 6]]

Grid + grid: 
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

Grid + grid: 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


x: [1 2 3]

y: 
[[99]
 [99]]

grid: 
[[9 8 7]
 [6 5 4]]

Vertical stacked using vstack of x and grid: 
[[1 2 3]
 [9 8 7]
 [6 5 4]]

Horizontally stacked using hstack of y and grid: 
[[ 9  8  7 99]
 [ 6  5  4 99]]



x: [1, 2, 3, 99, 99, 3, 2, 1]

All the arrays are splitted arrays are given below: 
[1 2 3] [99 99] [3 2 1]


grid: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Using vsplit (upper then lower) split at index 2 (exclusive): 

[[0 1 2 3]
 [4 5 6 7]]


[[ 8  9 10 11]
 [12 13 14 15]]

Using hsplit (left then right) split at index 2 (exclusive): 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
